version: '3'
services:
  apcupsd-influxdb-exporter:
    image: atribe/apcupsd-influxdb-exporter
    container_name: apcupsd-influxdb-exporter
    restart: always
    environment:
      WATTS: 1500 # if your ups doesn't have NOMPOWER, set this to be the rated max power, if you do have NOMPOWER, don't set this variable
      HOSTNAME: unraid # host you want to show up in influxdb
      INFLUXDB_DATABASE: apcupsd # db name for influxdb
      INFLUXDB_USER:
      INFLUXDB_PASSWORD:
      INFLUXDB_PORT: 8086
      INFLUXDB_HOST: localhost # host running influxdb
      APCUPSD_HOST: localhost # host running apcupsd


