version: '3'
services:
  apcupsd-influxdb-exporter:
    image: atribe/apcupsd-influxdb-exporter
    container_name: apcupsd-influxdb-exporter
    restart: always
    environment:
      WATTS: 1500 # if your ups doesn't have NOMPOWER, set this to be the rated max power, if you do have NOMPOWER, don't set this variable
      APCUPSD_HOST: localhost # host running apcupsd
      HOSTNAME: unraid # host you want to show up in influxdb, optional defaults to apcupsd-influxdb-exporter
      INFLUXDB_ORG:  # InfluxDB v2 organization name
      INFLUXDB_TOKEN:  # InfluxDB v2 access token
      INFLUXDB_URL:  # InfluxDB v2 host url
      INFLUXDB_BUCKET:  # InfluxDB v2 bucket name

